services:
  database:
    container_name: go_auth_users_grpc_postgres_container
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "${DB_NAME:-go_auth_grpc}"
      POSTGRES_USER: "${DB_USER:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASS:-postgres}"
    ports:
      - "${DB_PORT:-5444}:5432"
    restart: always
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: go_auth_users_grpc_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-admin}'
    ports:
      - "${PGADMIN_PORT:-5055}:80"
    depends_on:
      - database
    links:
      - database
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres

volumes:
    postgres:
    pgadmin:

networks:
  postgres:
    driver: bridge