CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL NOT NULL PRIMARY KEY,
	username  VARCHAR NOT NULL,
    slug  VARCHAR NOT NULL UNIQUE,
	hashed_password   BLOB NOT NULL,
    last_password_change TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_slug ON users (slug);