env: "local"
database: 
  driver: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5444
  db_name: "go_auth_grpc"
migration_path: "./migrations"
server:
  host: "localhost"
  port: 8001
  conn_timeout: 5s
token:
  ttl: 1h
  